### ISSUE TITLE
Document config params

### ISSUE THREAD

**Issue by cosmin-marginean** [logtail/logback-logtail#3]
We feel we need more documentation on things like `queueSize`, `discardingThreshold`, etc as it's unclear how any of these behave.

**Comment by gyfis** [comment]
@cosmin-marginean Hey Cos, thanks for raising the issue! For the `queueSize` and `discardingThreshold`, these are not unique to Logtail, but native to Logback instead. Here are the official docs: https://logback.qos.ch/manual/appenders.html#AsyncAppender. I updated our README with this link and a note - I'd close this if that's fine with you.

**Comment by cosmin-marginean** [comment]
Yes, sorry, I just assumed there was a specific reason for listing these in the docs. Thanks I'll close this.
